# Generated by Django 4.1.2 on 2022-11-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_registeredcollege_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredcollege',
            name='user_id',
            field=models.CharField(default='9bcb5073-37de-449e-bf4a-8e15954adb46', max_length=55, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registeredusers',
            name='user_id',
            field=models.CharField(default='e89a14ef-4f3f-49ba-a68b-f395d8a523fb', max_length=55, primary_key=True, serialize=False),
        ),
    ]
