# Generated by Django 4.1.3 on 2022-11-07 19:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_registeredcollege_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredcollege',
            name='user_id',
            field=models.CharField(default='9c6f9a42-7884-45ba-acc8-e7546e0eeea9', max_length=55, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registeredusers',
            name='email',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='registeredusers',
            name='password',
            field=models.CharField(max_length=260, null=True),
        ),
        migrations.AlterField(
            model_name='registeredusers',
            name='phone',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='registeredusers',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('f98c9e1b-70b3-4875-b191-9230423c28e3'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registeredusers',
            name='username',
            field=models.CharField(max_length=55),
        ),
    ]
