# Generated by Django 4.1.3 on 2022-11-07 19:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_registeredcollege_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredcollege',
            name='user_id',
            field=models.CharField(default='52f05959-a4d9-4256-aac3-dd164530e72d', max_length=55, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registeredusers',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
